import { loadOverrides } from '../support/overrides';

const ov = loadOverrides();

export type Scenario = {
  id: string;
  /** Destination the scenario asks for. */
  country: string;
  /** Requested travel type (Leisure/Business). */
  purpose: 'Leisure' | 'Business';
  departInDays: number;
  tripLengthDays: number;
  /** 1-based plan position (1 = first plan shown). */
  planPosition: number;
  /** Summary page, "registered with LHDN?" - Yes reveals the TIN/SST fields. */
  einvoice: 'Yes' | 'No';
  /** Tick the optional marketing declaration as well as the two mandatory ones. */
  marketing: 'Yes' | 'No';
};

const DEFAULT_SCENARIOS: Scenario[] = [
  { id: 'scenario-1-singapore-leisure', country: 'Singapore', purpose: 'Leisure', departInDays: 14, tripLengthDays: 7, planPosition: 1, einvoice: 'No', marketing: 'No' },
  { id: 'scenario-2-japan-business', country: 'Japan', purpose: 'Business', departInDays: 21, tripLengthDays: 10, planPosition: 2, einvoice: 'Yes', marketing: 'No' },
  { id: 'scenario-3-thailand-leisure', country: 'Thailand', purpose: 'Leisure', departInDays: 30, tripLengthDays: 14, planPosition: 3, einvoice: 'No', marketing: 'No' },
  // Domestic cover has a single plan (DOMESTIC), so planPosition must be 1.
  { id: 'scenario-4-malaysia-leisure', country: 'Malaysia', purpose: 'Leisure', departInDays: 10, tripLengthDays: 4, planPosition: 1, einvoice: 'No', marketing: 'Yes' },
  { id: 'scenario-5-australia-business', country: 'Australia', purpose: 'Business', departInDays: 45, tripLengthDays: 12, planPosition: 3, einvoice: 'Yes', marketing: 'No' },
  { id: 'scenario-6-united-states-leisure', country: 'United States', purpose: 'Leisure', departInDays: 60, tripLengthDays: 14, planPosition: 4, einvoice: 'No', marketing: 'No' },
];

/** Scenarios to run: the dashboard's list when supplied, otherwise the six defaults. */
export const SCENARIOS: Scenario[] = (ov.scenarios as Scenario[] | undefined) ?? DEFAULT_SCENARIOS;

/**
 * The funnel's "Destination" is a coverage area, not a country, and "Travel Type"
 * offers Individual / Group / Family / Senior Citizen (no Leisure / Business).
 * These maps record how the requested values are translated. All four coverage areas
 * (Domestic, Asia and both Worldwide areas) have been walked end to end; keep this list in
 * step with tests/travel/product.json.
 */
export const COVERAGE_AREA_BY_COUNTRY: Record<string, string> = {
  Malaysia: 'Domestic',
  Australia: 'Worldwide excluding USA & Canada',
  'United Kingdom': 'Worldwide excluding USA & Canada',
  France: 'Worldwide excluding USA & Canada',
  Germany: 'Worldwide excluding USA & Canada',
  'United States': 'Worldwide including USA & Canada',
  Canada: 'Worldwide including USA & Canada',
  Singapore: 'Asia',
  Japan: 'Asia',
  Thailand: 'Asia',
  'South Korea': 'Asia',
  Indonesia: 'Asia',
  Vietnam: 'Asia',
  Philippines: 'Asia',
  Cambodia: 'Asia',
  Brunei: 'Asia',
  India: 'Asia',
};
export const TRAVEL_TYPE = 'Individual'; // single adult participant, whatever the trip purpose

/** Dummy Malaysian citizen (default: born 1990-01-01, odd last digit = male). */
const DEFAULT_PARTICIPANT = {
  fullName: 'MUHAMMAD ADAM BIN AZLAN',
  nric: '900101105555',
  mobile: '0123456789',
  email: 'adam.azlan@example.com',
  addressLine1: 'No. 10 Jalan Mawar 1',
  addressLine2: 'Taman Mawar',
  postcode: '43000',
};

export const PARTICIPANT = { ...DEFAULT_PARTICIPANT, ...(ov.participant ?? {}) };

const DEFAULT_FLIGHT = {
  carrier: 'Malaysia Airlines',
  outboundNo: 'MH603',
  returnNo: 'MH604',
};

export const FLIGHT = { ...DEFAULT_FLIGHT, ...(ov.flight ?? {}) };

/**
 * E-invoice details (Summary page). TIN is required when the participant answers "Yes"
 * (min 10 characters); SST is optional. Placeholders only: nothing here is a real tax number.
 */
export const EINVOICE = {
  tin: (ov.einvoice?.tin as string | undefined) ?? 'IG00000000000',
  sst: (ov.einvoice?.sst as string | undefined) ?? '',
};

/**
 * Auto Credit (bank) is mandatory on the Flight Details step. Only the bank name is
 * chosen here; the dummy account number is generated by the test to match the length
 * the site itself lists for that bank (GET /api/v1/refs/banks).
 */
export const BANK = {
  name: (ov.bank?.bankName as string | undefined) ?? process.env.BANK_NAME ?? 'RHB BANK BERHAD',
};

/** Age (years) encoded in a Malaysian NRIC's YYMMDD prefix, as of `today`. */
export function ageFromNric(nric: string, today = new Date()): number {
  const yy = Number(nric.slice(0, 2));
  const mm = Number(nric.slice(2, 4));
  const dd = Number(nric.slice(4, 6));
  const thisYY = today.getFullYear() % 100;
  const year = (yy > thisYY ? 1900 : 2000) + yy;
  let age = today.getFullYear() - year;
  if (today.getMonth() + 1 < mm || (today.getMonth() + 1 === mm && today.getDate() < dd)) age--;
  return age;
}

/** NRIC last digit: odd = male, even = female. */
export function genderFromNric(nric: string): 'Male' | 'Female' {
  return Number(nric.slice(-1)) % 2 === 1 ? 'Male' : 'Female';
}
